### ISSUE TITLE
if template without lang="pug" have custom element will show error

### ISSUE THREAD

**Issue by ausir0726** [sourceboat/pug-lint-vue#2]
I have a test.vue file have a custom element like this

``` 
<template>
  <div>
    <mycomponent></mycomponent>
  </div>
</template>
<script></script>
<style scoped></style>
```

it should skip pug-lint-vue

but it will got error 
```
λ yarn pug-lint-vue pages/test.vue
yarn pug-lint-vue v0.21.3
$ "C:\Users\ausir\vts\node_modules\.bin\pug-lint-vue" pages/test.vue
C:\Users\ausir\vts\node_modules\domutils\lib\querying.js:89
                if(elems[i].children.length > 0){
                                    ^

TypeError: Cannot read property 'length' of undefined
    at findAll (C:\Users\ausir\vts\node_modules\domutils\lib\querying.js:89:23)
    at findAll (C:\Users\ausir\vts\node_modules\domutils\lib\querying.js:90:27)
    at Object.findAll (C:\Users\ausir\vts\node_modules\domutils\lib\querying.js:90:27)
    at selectAll (C:\Users\ausir\vts\node_modules\css-select\index.js:26:70)
    at select (C:\Users\ausir\vts\node_modules\css-select\index.js:21:10)
    at CSSselect (C:\Users\ausir\vts\node_modules\css-select\index.js:41:9)
    at initialize.exports.find (C:\Users\ausir\vts\node_modules\cheerio\lib\api\traversing.js:40:21)
    at initialize.module.exports (C:\Users\ausir\vts\node_modules\cheerio\lib\cheerio.js:86:18)
    at new initialize (C:\Users\ausir\vts\node_modules\cheerio\lib\static.js:29:20)
    at initialize (C:\Users\ausir\vts\node_modules\cheerio\lib\static.js:26:14)
error Command failed with exit code 1.
```

if I delete that custom element , pug-lint-vue work well .
but, sometimes I will import some vue component , that use html and custom element ....

how can I fix it ?

thanks.

**Comment by pehbehbeh** [comment]
I try to look into it as soon as I can and provide an easy fix.

**Comment by ausir0726** [comment]
@pehbehbeh 

is possible have a option also lint .pug file ?
because sometimes out pug template is too long we will link to .pug file 
or , if pug-lint-vue find src="file.pug" , it will auto find file.pug and lint it .

```
<template lang="pug" src="file.pug"></template>
<script></script>
<style lang="stylus"></style>
```

and ...

is possible add a loader for webpack ? 
I tried this https://github.com/pugjs/pug-lint/issues/120
but it only lint .pug file .

thanks ! I am a starter for use linter and loader .

**Comment by Jack-Works** [comment]
@ausir0726 

Umm. An inline lint? I have no idea about how to solve it at present, maybe I can work on it later.

You can try to extract your pug code into a separate file and include it in <template>.
I think that will be an acceptable solution.

**Comment by krns** [comment]
Hey @ausir0726, 
I tried to reproduce your problem but I'm not seeing your error though. Do you have any other steps for reproduction?

**Comment by pehbehbeh** [comment]
Closed because no recent activity. Please check again with latest version and provide more information if still valid.
