### ISSUE TITLE
Error on run

### ISSUE THREAD

**Issue by FPierre** [sourceboat/pug-lint-vue#3]
Hey there

The following command:

```
$ (master) pug-lint-vue src/components/LayoutFooter.vue 
```

Gives me:

```
/usr/lib/node_modules/pug-lint-vue/node_modules/domutils/lib/querying.js:89
                if(elems[i].children.length > 0){
                                    ^

TypeError: Cannot read property 'length' of undefined
    at Object.findAll (/usr/lib/node_modules/pug-lint-vue/node_modules/domutils/lib/querying.js:89:23)
    at selectAll (/usr/lib/node_modules/pug-lint-vue/node_modules/css-select/index.js:26:70)
    at select (/usr/lib/node_modules/pug-lint-vue/node_modules/css-select/index.js:21:10)
    at CSSselect (/usr/lib/node_modules/pug-lint-vue/node_modules/css-select/index.js:41:9)
    at initialize.exports.find (/usr/lib/node_modules/pug-lint-vue/node_modules/cheerio/lib/api/traversing.js:40:21)
    at initialize.module.exports (/usr/lib/node_modules/pug-lint-vue/node_modules/cheerio/lib/cheerio.js:86:18)
    at new initialize (/usr/lib/node_modules/pug-lint-vue/node_modules/cheerio/lib/static.js:29:20)
    at initialize (/usr/lib/node_modules/pug-lint-vue/node_modules/cheerio/lib/static.js:26:14)
    at DefaultHandler.htmlparser.DefaultHandler [as _callback] (/usr/lib/node_modules/pug-lint-vue/lib/linter.js:68:36)
    at DefaultHandler$handleCallback [as handleCallback] (/usr/lib/node_modules/pug-lint-vue/node_modules/htmlparser/lib/htmlparser.js:644:9)
```

It's looks like [this other linter issue](https://github.com/sourceboat/sass-lint-vue/issues/2).

I will make a PR :)

**Comment by pehbehbeh** [comment]
Can you post your `LayoutFooter.vue`?

Is this related to #2 (no `lang="pug"` in your file)?

**Comment by FPierre** [comment]
Exactly the same as [this issue](https://github.com/sourceboat/sass-lint-vue/issues/2#issuecomment-293156534).
It's not related to #2, my file contains `<script lang="pug">` tag
